### ISSUE TITLE
Recent change broke cert_link value (http://https://)

### ISSUE THREAD

**Issue by freddieleeman** [CaliDog/CertStream-Server#94]
As of this morning, the `cert_link` value is broken. Possibly due to a recent update. There is an `http://` prefix that doesn't belong there.

`"cert_link": "http://https://ct.cloudflare.com/logs/nimbus2023/ct/v1/get-entries?start=85295232&end=85295232"`

The issue can also be seen here: https://certstream.calidog.io/example.json

**Comment by alexmaurizio** [comment]
Yep, this is caused by this: https://github.com/CaliDog/certstream-server/commit/87ef27ed37054e46fe3c8d446dba103d51379cdd#diff-4b994598b68faf5d6ffc6e9d6056f580b308fa2a3f196f50f6185d4f13314ac6R171 (check inline prefix on line 188)

Even if wrong, changing between http and https should be considered a change that can break systems that rely on the cert_link info as a tag/id for historical matches.

**Comment by freddieleeman** [comment]
I could change the PR to force `http://` if that is preferred, but the current state breaks it either way.
